import copy
import logging
import os
import time

import torch
from torch.optim import AdamW
from torch.utils.tensorboard import SummaryWriter
from torchmetrics.aggregation import MeanMetric
from torchvision.utils import save_image
from tqdm.auto import tqdm

import data
import util
from components.buffer import BatchBuffer
from components.matchers import AdjointMatcher, CorrectorMatcher, ScoreMatcher
from components.prior import GaussianPrior, TerminalCost
from components.sdes import ControlledSDE, FlowMatching, build_reference_sde, sdeint
from models.unet import UNetModelWrapper


def build_unet(num_res_blocks, dim):
    return UNetModelWrapper(
        dim=dim,
        num_res_blocks=num_res_blocks,
        num_channels=128,
        channel_mult=[1, 2, 2, 2],
        num_heads=4,
        num_head_channels=64,
        attention_resolutions="16",
        dropout=0.1,
    )


def build_optimizer(opt, model, lr):
    return AdamW(model.parameters(), lr=lr, weight_decay=opt.l2_norm)


def ema_update(source, target, decay):
    source_dict = source.state_dict()
    target_dict = target.state_dict()
    for key in source_dict.keys():
        target_dict[key].data.copy_(target_dict[key].data * decay + source_dict[key].data * (1 - decay))


def freeze(model):
    for p in model.parameters():
        p.requires_grad = False
    model.eval()
    return model


def build_logger(log_dir):
    logger = logging.getLogger("train")
    logger.handlers.clear()
    logger.setLevel(logging.INFO)
    logger.propagate = False
    if log_dir is not None:
        fh = logging.FileHandler(os.path.join(log_dir, "train_log.txt"))
        fh.setFormatter(logging.Formatter("%(asctime)s | %(levelname)s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S"))
        logger.addHandler(fh)
    return logger


class Runner:
    """ASBM.

    Stage 1 learns the forward control u_f (t: data -> prior) of a Schrodinger bridge with the reference SDE
    by alternating adjoint matching (u_f) and corrector matching (corrector h at t=1).
    Stage 2 learns the backward score s_b by bridge score matching on the coupling (x0, x1) simulated
    with the learned forward process. Samples are generated by integrating the backward process from the prior.

    Networks: z_f (forward control), z_b (corrector in stage 1, score network in stage 2), and their EMAs.
    """

    def __init__(self, opt):
        self.opt = opt
        self.device = device = opt.device
        self.data_dim = opt.data_dim
        self.start_time = time.time()

        # ---------- logging ----------
        self.logger = build_logger(None if opt.eval_fid else opt.ckpt_path)
        self.writer = SummaryWriter(log_dir=opt.ckpt_path) if (opt.log_tb and not opt.eval_fid) else None
        self.eigen_best = float("inf")
        self.best_epoch = None

        # ---------- networks ----------
        # z_b is the corrector during stage 1 and is replaced by a (larger) score network for stage 2.
        # Build the score network directly for the score-matching baseline, or when loading a stage-2 checkpoint
        # (evaluation, distillation teacher, resuming stage 2).
        score_net = opt.score_matching or (opt.load is not None and (
            opt.eval_fid or opt.distill or (opt.start_from_sm and not opt.reinit_score_model)))
        self.z_f = build_unet(opt.num_res_blocks, opt.data_dim).to(device)
        self.z_b = build_unet(opt.num_res_blocks_sm if score_net else opt.num_res_blocks, opt.data_dim).to(device)
        self.optimizer_f = build_optimizer(opt, self.z_f, opt.lr_f)
        self.optimizer_b = build_optimizer(opt, self.z_b, opt.lr_sm if score_net else opt.lr_b)
        self.ema_f = copy.deepcopy(self.z_f)
        self.ema_b = copy.deepcopy(self.z_b)

        # ---------- reference process, controlled SDEs, prior ----------
        self.ref_sde = build_reference_sde(opt)
        self.sde_f = ControlledSDE(self.ref_sde, self.z_f).to(device)
        self.sde_f_ema = ControlledSDE(self.ref_sde, self.ema_f).to(device)
        self._build_backward_sdes()
        self.prior = GaussianPrior(std=opt.prior_std)

        # ---------- matchers ----------
        sim_sde = self.sde_f_ema if opt.simulate_ema else self.sde_f
        self.adjoint_matcher = AdjointMatcher(
            terminal_cost=TerminalCost(self.prior, corrector=self.z_b),
            sde=sim_sde,
            buffer=BatchBuffer(opt.buffer_size),
            resample_size=opt.forward_resample_size,
            duplicates=opt.dataloader_duplicate,
            min_t0=0.0,
        )
        self.corrector_matcher = CorrectorMatcher(
            sde=sim_sde,
            buffer=BatchBuffer(opt.buffer_size),
            resample_size=opt.forward_resample_size,
            duplicates=opt.dataloader_duplicate,
            min_t0=0.0,
        )
        self.score_matcher = ScoreMatcher(
            flow_matching=opt.flow_matching,
            sde=sim_sde,
            buffer=BatchBuffer(opt.backward_buffer_size),
            resample_size=opt.backward_resample_size,
            duplicates=1,
            min_t0=1e-5,
        )

        # ---------- latent diffusion (FFHQ) ----------
        if opt.ldm:
            from diffusers.models import AutoencoderKL
            self.vae = AutoencoderKL.from_pretrained(opt.vae_model).eval()  # kept on CPU unless decoding
            self.latent_scaling_factor = getattr(self.vae.config, "scaling_factor", 0.18215)
            self.latent_shift_factor = getattr(self.vae.config, "shift_factor", None)

        # ---------- checkpoint ----------
        if opt.load is not None:
            loaded = util.restore_checkpoint(self, opt.load)
            # released checkpoints only contain the EMA networks
            if "z_f" not in loaded and "ema_f" in loaded:
                self.z_f.load_state_dict(self.ema_f.state_dict())
            if "z_b" not in loaded and "ema_b" in loaded:
                self.z_b.load_state_dict(self.ema_b.state_dict())
            # use the learning rates of the current run
            for optimizer, lr in [(self.optimizer_f, opt.lr_f), (self.optimizer_b, opt.lr_sm if score_net else opt.lr_b)]:
                for pg in optimizer.param_groups:
                    pg["lr"] = lr
        if opt.start_from_sm and opt.reinit_score_model:
            self._reinit_score_model()

    # ------------------------------------------------------------------ utils
    def _build_backward_sdes(self):
        ref = FlowMatching() if self.opt.flow_matching else self.ref_sde
        self.sde_b = ControlledSDE(ref, self.z_b).to(self.device)
        self.sde_b_ema = ControlledSDE(ref, self.ema_b).to(self.device)

    def _reinit_score_model(self):
        opt = self.opt
        self.print_log(f"Initialize the score network ({opt.num_res_blocks_sm} res-blocks)")
        self.z_b = build_unet(opt.num_res_blocks_sm, opt.data_dim).to(self.device)
        self.optimizer_b = build_optimizer(opt, self.z_b, opt.lr_sm)
        self.ema_b = copy.deepcopy(self.z_b)
        self._build_backward_sdes()

    def print_log(self, string):
        print(string)
        self.logger.info(string)

    def save(self, fn):
        keys = ["z_b", "optimizer_b", "ema_b"]
        if not self.opt.score_matching:  # the score-matching baseline has no forward process
            keys = ["z_f", "optimizer_f", "ema_f"] + keys
        util.save_checkpoint(self, keys, os.path.join(self.opt.ckpt_path, fn))

    def encode(self, x0):
        """Data -> diffusion space. For LDM, x0 is a sampled VAE latent and is scaled here."""
        if self.opt.ldm:
            if self.latent_shift_factor is not None:
                x0 = x0 - self.latent_shift_factor
            x0 = x0 * self.latent_scaling_factor
        return x0

    @torch.no_grad()
    def decode(self, x, chunk=64):
        """Diffusion space -> images in [-1, 1]."""
        if not self.opt.ldm:
            return x
        self.vae.to(self.device)
        out = []
        for z in torch.split(x, chunk):
            z = z / self.latent_scaling_factor
            if self.latent_shift_factor is not None:
                z = z + self.latent_shift_factor
            out.append(self.vae.decode(z).sample.detach())
        return torch.cat(out, dim=0)

    def forward_timesteps(self, nfe):
        return torch.linspace(0.0, 1.0, steps=nfe).to(self.device)

    def backward_timesteps(self, nfe):
        """`nfe` uniform steps from t=1 to t=0."""
        return torch.linspace(1.0, 0.0, steps=nfe + 1).to(self.device)

    @torch.no_grad()
    def sample(self, batch_size, nfe, sampler):
        """Generate samples (in diffusion space) with the EMA networks; the last step is noise-free."""
        x1 = self.prior.sample(batch_size, self.data_dim, device=self.device)
        timesteps = self.backward_timesteps(nfe)
        _, x0 = sdeint(
            None if self.opt.score_matching else self.sde_f_ema,  # forward control (used by the ODE sampler)
            x1,
            timesteps,
            zero_last_step_noise=True,
            only_boundary=True,
            pf_ode="heun" if sampler == "heun" else None,
            backward_sde=self.sde_b_ema,
        )
        return x0

    # ------------------------------------------------------------------ stage 1
    def train_one_epoch(self, stage, epoch, is_init_stage):
        opt, device = self.opt, self.device
        matcher, model, optimizer, ema = {
            "adjoint": (self.adjoint_matcher, self.z_f, self.optimizer_f, self.ema_f),
            "bridge": (self.corrector_matcher, self.z_b, self.optimizer_b, self.ema_b),
        }[stage]

        # simulate and fill the replay buffer
        nfe = opt.cm_nfe if stage == "bridge" else opt.forward_nfe
        for _ in range(matcher.resample_size // opt.samp_bs):
            x0 = self.data_sampler.sample().to(device)
            with torch.no_grad():
                x0 = self.encode(x0)
            matcher.populate_buffer(x0, self.forward_timesteps(nfe), is_init_stage, opt.fwd_zero_noise)

        dataloader = matcher.build_dataloader(opt.asbs_bs if stage == "adjoint" else opt.cm_bs)
        epoch_loss = MeanMetric().to(device)
        model.train(True)
        pbar = tqdm(dataloader, desc=f"Train {stage}", total=len(dataloader))
        for batch in pbar:
            optimizer.zero_grad()
            inputs, target = matcher.prepare_target(batch, device)
            output = model(*inputs)
            loss = ((output - target) ** 2).mean()
            loss.backward()
            optimizer.step()
            ema_update(model, ema, opt.ema_decay_fwd)

            epoch_loss.update(loss.item())
            pbar.set_postfix(loss=float(loss.item()))
        return float(epoch_loss.compute().detach().cpu())

    def train_forward(self):
        opt = self.opt
        n_a, n_b = opt.forward_am_epochs, opt.forward_cm_epochs

        def stage_of(epoch):
            if opt.init_stage == "adjoint":
                return "adjoint" if (epoch % (n_a + n_b)) < n_a else "bridge"
            return "bridge" if (epoch % (n_a + n_b)) < n_b else "adjoint"

        n_init = n_a if opt.init_stage == "adjoint" else n_b
        for epoch in range(opt.forward_epochs):
            stage, next_stage = stage_of(epoch), stage_of(epoch + 1)
            # the very first stage starts from the reference process (zero control / zero corrector)
            is_init_stage = opt.load is None and epoch < n_init

            loss = self.train_one_epoch(stage, epoch, is_init_stage)
            print("[{0} | {1}] {2}".format(util.cyan(f"{stage:<7}"), util.yellow(f"ep={epoch:04}"), util.green(f"loss={loss:.4f}")))
            self.logger.info(f"[{stage} | ep={epoch}] loss={loss:.4f}")
            if self.writer is not None:
                self.writer.add_scalar(f"train/loss_{stage}", loss, epoch)

            last_epoch = epoch + 1 == opt.forward_epochs
            if stage != next_stage:
                if opt.reset_buffer:
                    self.adjoint_matcher.buffer.reset()
                    self.corrector_matcher.buffer.reset()
                if opt.reset_optimizer:
                    self.optimizer_f = build_optimizer(opt, self.z_f, opt.lr_f)
                    self.optimizer_b = build_optimizer(opt, self.z_b, opt.lr_b)

            if stage != next_stage or last_epoch:
                self.save(f"forward_{stage}_{epoch + 1}ep.pt")
                self.z_f.eval()
                self.z_b.eval()

                if opt.do_forward_eval and epoch >= opt.forward_eval_start and (stage == "adjoint" or last_epoch):
                    eigen_max, is_training_enough = self.evaluate_forward()
                    if eigen_max <= self.eigen_best and is_training_enough:
                        self.print_log(f"Save {epoch + 1} epoch as best epoch with eigen max {eigen_max}")
                        self.save("forward_best.pt")
                        self.eigen_best, self.best_epoch = eigen_max, epoch + 1
                    self.print_log(f"Epoch {epoch + 1}: best epoch: {self.best_epoch}, best eigen max: {self.eigen_best}")
                    if is_training_enough:
                        self.print_log("Terminal marginal matches the prior. Finish the forward training.")
                        return

        self.print_log("Forward training finished.")

    @torch.no_grad()
    def evaluate_forward(self):
        """Simulate the forward SDE from (up to 51,200) data points and compare the terminal samples with the prior:
        max eigenvalue of the sample covariance (vs. that of prior samples) and the radial statistics of ||x1||^2."""
        opt, device = self.opt, self.device
        dataset = self.dataset
        max_samples = 51200
        if len(dataset) > max_samples:
            dataset = torch.utils.data.Subset(dataset, torch.randperm(len(dataset))[:max_samples].tolist())
        loader = data.build_loader(dataset, opt.samp_bs, shuffle=False)
        sde = self.sde_f_ema if opt.simulate_ema else self.sde_f

        generations = []
        for batch in tqdm(loader, desc="Evaluate forward"):
            x0 = self.encode(batch[0].to(device))
            _, x1 = sdeint(sde, x0, self.forward_timesteps(opt.forward_nfe), zero_last_step_noise=False, only_boundary=True)
            generations.append(x1)
        generations = torch.cat(generations, dim=0)

        B = generations.shape[0]
        self.print_log(f"Stat: ({generations.mean()}, {generations.std()})")
        eigen_eval = cov_eigenspectrum_test(generations)
        eigen_eval_gt = cov_eigenspectrum_test(self.prior.sample(B, self.data_dim, device=device))
        radial_eval = radial_check(generations, std=opt.prior_std)
        self.print_log(f"{eigen_eval}\n<prior samples> {eigen_eval_gt}\n{radial_eval}")

        eigen_max = eigen_eval["eigen_max"]
        is_eigen_enough = eigen_max / (opt.prior_std**2) <= eigen_eval_gt["eigen_max"]
        is_stat_enough = radial_eval["mean_error"] < 0.08 and radial_eval["var_error"] < 0.08
        return eigen_max, is_eigen_enough and is_stat_enough

    # ------------------------------------------------------------------ stage 2
    def train_backward(self):
        opt, device = self.opt, self.device
        matcher = self.score_matcher
        model, optimizer, ema = self.z_b, self.optimizer_b, self.ema_b

        for epoch in range(opt.backward_epochs):
            # simulate fresh couplings (x0, x1) with the (frozen) forward SDE
            for _ in range(matcher.resample_size // opt.samp_bs):
                x0 = self.data_sampler.sample().to(device)
                with torch.no_grad():
                    x0 = self.encode(x0)
                matcher.populate_buffer(x0, self.forward_timesteps(opt.forward_nfe), False, opt.fwd_zero_noise)
            dataloader = matcher.build_dataloader(opt.sm_bs, duplicates=1)

            epoch_loss = MeanMetric().to(device)
            model.train(True)
            pbar = tqdm(dataloader, desc="Train score", total=len(dataloader))
            for batch in pbar:
                optimizer.zero_grad()
                inputs, target, weight = matcher.prepare_target(batch, device)
                output = model(*inputs)
                loss = ((weight * output - target) ** 2).mean()
                loss.backward()
                optimizer.step()
                ema_update(model, ema, opt.ema_decay_bwd)

                epoch_loss.update(loss.item())
                pbar.set_postfix(loss=float(loss.item()))

            self._end_of_backward_epoch(epoch, float(epoch_loss.compute().detach().cpu()))

    def train_score_matching(self):
        """Baseline: denoising score matching on the VP reference SDE (memoryless diffusion, no forward process)."""
        opt, device = self.opt, self.device
        model, optimizer, ema = self.z_b, self.optimizer_b, self.ema_b
        loader = data.build_loader(self.dataset, opt.sm_bs, shuffle=True)

        for epoch in range(opt.backward_epochs):
            epoch_loss = MeanMetric().to(device)
            model.train(True)
            pbar = tqdm(loader, desc="Train score (DSM)", total=len(loader))
            for batch in pbar:
                optimizer.zero_grad()
                with torch.no_grad():
                    x0 = self.encode(batch[0].to(device))
                t = self.score_matcher.sample_t(x0.shape[0]).to(device)
                xt, eps, sigma_t = self.ref_sde.sample_marginal(t, x0)
                sigma_t = sigma_t.reshape(sigma_t.shape[0], *([1] * (xt.ndim - 1)))
                output = model(t, xt)
                loss = ((sigma_t * output + eps) ** 2).mean()  # sigma_t * score  vs.  -eps
                loss.backward()
                optimizer.step()
                ema_update(model, ema, opt.ema_decay_bwd)

                epoch_loss.update(loss.item())
                pbar.set_postfix(loss=float(loss.item()))

            self._end_of_backward_epoch(epoch, float(epoch_loss.compute().detach().cpu()))

    def _end_of_backward_epoch(self, epoch, avg_loss):
        opt = self.opt
        print("[{0} | {1}] {2}".format(util.cyan("score  "), util.yellow(f"ep={epoch:04}"), util.green(f"loss={avg_loss:.4f}")))
        self.logger.info(f"[score | ep={epoch}] loss={avg_loss:.4f}")
        if self.writer is not None:
            self.writer.add_scalar("train/loss_score", avg_loss, epoch)

        if epoch < 10 or (epoch + 1) % opt.backward_save_freq == 0:
            self.save(f"backward_{epoch + 1}ep.pt")
            self.z_b.eval()
            x = self.sample(64, opt.sample_nfe, opt.sampler)
            x = (self.decode(x).clip(-1, 1) + 1) / 2
            save_image(x, os.path.join(opt.ckpt_path, f"backward_{epoch + 1}ep_samples.png"), nrow=8)

    # ------------------------------------------------------------------ entry points
    def train(self):
        opt = self.opt
        self.dataset = data.build_dataset(opt)
        self.data_sampler = data.DataSampler(self.dataset, opt.samp_bs, shuffle=True)

        if opt.score_matching:
            self.print_log("Score-matching baseline.")
            self.train_score_matching()
            if self.writer is not None:
                self.writer.close()
            return

        if opt.start_from_sm:
            self.print_log("Start from stage 2 (score matching).")
        else:
            self.print_log("Stage 1: forward process (adjoint / corrector matching).")
            self.train_forward()
            if self.best_epoch is not None:
                self.print_log(f"Load the best forward model (epoch {self.best_epoch}).")
                util.restore_checkpoint(self, os.path.join(opt.ckpt_path, "forward_best.pt"))
            else:
                self.print_log("No forward model passed the terminal-marginal check; use the last forward model.")
            self._reinit_score_model()

        self.print_log("Stage 2: backward process (score matching).")
        self.z_f = freeze(self.z_f)
        self.train_backward()
        if self.writer is not None:
            self.writer.close()

    @torch.no_grad()
    def generate(self, out_dir, num_samples, batch_size, nfe, sampler):
        os.makedirs(out_dir, exist_ok=True)
        n_written = 0
        pbar = tqdm(total=num_samples, desc="Generating")
        while n_written < num_samples:
            x = self.sample(batch_size, nfe, sampler)
            x = (self.decode(x).clip(-1, 1) + 1) / 2
            x = x[: num_samples - n_written].cpu()
            for i in range(x.shape[0]):
                save_image(x[i], os.path.join(out_dir, f"{n_written + i + 1:06d}.png"))
            n_written += x.shape[0]
            pbar.update(x.shape[0])
        pbar.close()


@torch.no_grad()
def cov_eigenspectrum_test(samples):
    B = samples.shape[0]
    d = samples[0].numel()
    X = samples.reshape(B, d).to(dtype=torch.float32)
    mu = X.mean(dim=0)
    Xc = X - mu
    Sigma = ((Xc.T @ Xc) / (B - 1)).cpu()
    del Xc
    torch.cuda.empty_cache()
    evals = torch.linalg.eigvalsh(Sigma)
    return {
        "B": int(B),
        "d": int(d),
        "mean_norm": float(mu.norm().item()),
        "eigen_min": float(evals.min().item()),
        "eigen_max": float(evals.max().item()),
        "eigen_mean": float(evals.mean().item()),
        "participation_ratio": float((evals.sum() ** 2 / (evals**2).sum()).item()),
    }


@torch.no_grad()
def radial_check(samples, std=1.0):
    # for N(0, std^2 I_d): E||z||^2 = d std^2, Var||z||^2 = 2 d std^4
    B = samples.shape[0]
    d = samples[0].numel()
    sqnorms = (samples.reshape(B, d).to(torch.float32) ** 2).sum(dim=1)
    expected_mean, expected_var = d * std**2, 2 * d * std**4
    mean_sqnorm, var_sqnorm = float(sqnorms.mean()), float(sqnorms.var(unbiased=False))
    return {
        "mean_sqnorm": mean_sqnorm,
        "var_sqnorm": var_sqnorm,
        "mean_error": abs(mean_sqnorm - expected_mean) / expected_mean,
        "var_error": abs(var_sqnorm - expected_var) / expected_var,
    }
